### ISSUE TITLE
Crash on dub build

### ISSUE THREAD

**Issue by SolarLune** [SaurabhTotey/d2d-Basics#1]
Hey, there. Getting an error on trying to build a project using d2d as a dependency / requirement. Here's the error:

```
> Executing task: dub <

Fetching derelict-sdl2 3.1.0-alpha.3 (getting selected version)...
Fetching d2d 1.4.8 (getting selected version)...
Fetching derelict-util 3.0.0-beta.2 (getting selected version)...
Performing "debug" build using dmd for x86_64.
derelict-util 3.0.0-beta.2: building configuration "library"...
derelict-sdl2 3.1.0-alpha.3: building configuration "derelict-sdl2-dynamic"...
d2d 1.4.8: building configuration "library"...
../../../../.dub/packages/d2d-1.4.8/d2d/source/d2d/math/Vector.d(192,16): Error: basic type expected, not foreach
../../../../.dub/packages/d2d-1.4.8/d2d/source/d2d/math/Vector.d(192,16): Error: no identifier for declarator _error_
../../../../.dub/packages/d2d-1.4.8/d2d/source/d2d/math/Vector.d(204,16): Error: basic type expected, not foreach
../../../../.dub/packages/d2d-1.4.8/d2d/source/d2d/math/Vector.d(204,16): Error: no identifier for declarator _error_
dmd failed with exit code 1.
The terminal process terminated with exit code: 2
```

I have D version 2.073.0:
```
DMD64 D Compiler v2.073.0-devel-1db00f2ef-dirty
Copyright (c) 1999-2016 by Digital Mars written by Walter Bright
```

**Comment by KadinTucker** [comment]
Hi SolarLune,
The error comes from the swizzling overload on vector, so we are going to temporarily remove the feature from d2d until we can fix the problem.
Previously this was only a runtime issue, but now it will happen regardless of whether or not swizzling is used. The latest version of d2d (1.4.9) will be released about an hour from me sending this. Make sure to use 'dub upgrade' to upgrade d2d in your project once it is.
Thanks for letting us know,
Kadin

**Comment by SolarLune** [comment]
Hey, thanks for letting me know as well! I'll go ahead and close this and re-open if I still have issues or anything.

Thanks again.
